name: Python CI

on: [push]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.139.com
          server_port: 465
          username: ${{ secrets.EMAIL_139_USER_NAME }}
          password: ${{ secrets.EMAIL_139_USER_PWD }}
          subject: Github Actions job result
          body: github action send email test!!!!
          #html_body:file://test.html
          to: 1379126606@qq.com
          from: GitHub Actions